name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2.4.1
      with:
        node-version: '14.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: 'MIIJKQIBAAKCAgEAxbtk6R7qvSDR26g3xpOGxJmRkRctCLm9zxNReC3a+7meum6HI5A+sjNZJVYbbURZioBCaYQaBaZQlyhX0pDFMwobfqRNF0OjoFl2Ax9hVTW4vtkT
l/TD6beaJFYjNQSzZhYXMULac3ALH114rcPRF1FqqAj/S6RWkj8sZ7xsVRh6VEer
PhAdyOAFUCN6E+YM0WDlD8tLUp7a/v8JJTOUsm1aUsnCsHvkSYAKd7wiA5RXOx06
Kz7w3rbt5LjkwAMXkAKy7JBM4cmQzP9r9w/8gQaVTNl8fb4EwX4xtapj8ZjQ2AL7
m0V6O0TXY2ariMYCTa8E1Qybd91xnjUWhBWqmGZ1qyNEyU0lnRbbML9k7rx+oWAw
2NrE5mJlSwoOyYp5oBOUiwon1TW+OQh+Xw3siIDB5/FrexN9vJCIEW5uvtKlSGEy
61msF7RK+ec4bV0kv/gzonaUzeVGbHKHJVaQ2u94qJIBIRbeZh18u6yS77SRfADk
PPMTvsNg3sa84sEPFZw3inK3KBk89uucRMGHMHm+kvDiFAouapQPC+Yy96v+RUr5
xMg618vuACZxFxA57ydbd5TGxkWYkzpfHY79UKOXz5ZK+Ba6OmO8s2F2rk5wRjMx
F5jWtzclImBWMy2x79zikGz21z4GYvdNaC+bkPC71uHutjbA2Xe1LqBynRMCAwEA
AQKCAgApX6GoychSVJi0vokVKu9LGdsEofXRWpQlzSQB4o5sl5Vn6xKp1VfZD7d6
gX7xqRiXS2kaDQMo5Xj9d/qQW6x3lojUQerDkGqfdbikxJ8oJjqG7IMWC6gmsj01
lzR8toQXO04VB6kP+ITLRlKnAU8x8t4/VMqeeD+JEGDpP9rnH10RX4GsVdD1pDJY
Z2P23+8UrJKhcGdNXWHzc0flmdpmT01T/1WWegX1fy4xiZMQbqyl+OKgA+aAo4Q5
lJqAtuTqRDZOG4+KuxNqYZOkuZqbINaCowtSgD0cg5xBJ+sLtW8Vk+IzxiDiX/A1
o1kHIG+A87suHRo2xYYtlWwlrSbpqGOD9phCKhhGF1v0JCE67Rk5LVP4h5kO58Rv
xL5T2VfMoh0/hbfeIPfwfRBhSRwQnYX8oVbYUCkdPWzQnmqNR7al9uQcSKYFR/J+
qGYtfyyN7GTsV9arvSkMbmP/60eGUJ6TJ7Y+nCOf6um6cJSRtIsv3ytuPV3wRTns
acf9Tjbe8uG29jy3MXfvWAi2tHNd8xKoYZVbWPD8tMmIWIXkVjj3T8yPOdGQJnGG
OMWxFI1HTJCuEr7Kxk9nUCu22fxkLsMo8h3YNpiecn0ehGX5R17ouwo5kHMDu4To
I9zi9JkWzknWPHPkTu+7LFSJ7LPGcYuF0xO1imj+tGcf99z9aQKCAQEA6kNiTzKV
jf5i4RWj4xDeRBwC9ly50Any4gxwk0Itcr4kQuLsOGHLnjUSSBcjjvbQUdjnk6tB
EtkHOWTvrE6zgveXmPiT0vawjhOBfEJL1WaNyjxlUrF6Mgccwfle9Gm3wJppRFD3
McN2eDXQmyyTQREfOFL9k1lQgKYENANS9LJAlYdIieJZ6/c8eWqbf55X7IXKfGy6
ED7TRbmBctbf2S7bUT5IZ5RFjRkw7Uv/AGyVK5IjNuIE4qIv+qE8PXwDmubz5FKx
7M6Fw6tI2Gy53QoLKFDmD4zw6bBbJJ9Xbvy/Wzj0rN8dQtoG4wj36bFrJz667fJk
u/lnJpagAq3+zQKCAQEA2BRCVGmOYBEaEePgh+vphZS9BPEUIQJnjChmGbd8FSAW
k/e6Icd1iSjoOyHCvU5Jni5tKN+ArlhUEV9Rahmz3Ql9OoO5Y/rLdI21CUEH1gAA
F9i4ivmIFj/46SE2WfL8RoEiKB6st06lhZ87X60lfT+TRRlG04/8SXJojU2xqLPh
QjDniV30RpDQ8SzsnCuFoxI5abqc0oVH7p3g4mUhlb17eOKm11RpgsWQSVT/+ZR9
gzBZP/1B4R7LDadiYPU/T06cnAUJgHh7uM/QsqkI0ovYeWTD6+JKzQ/ASvwMAy7E
82DnXucLMSSXcY8NLTjQR5z4IscCJ8Ap6c/AMydLXwKCAQAk/wtRkp2H1TrsbSx6
ublAbGQTYEWAE3ImPOyydOsUie7UGV5Q8TDlBWCjvfPBqjzwEB9SdONMBLZdXBF1
1uAGuO9aGzfNQ2RSq8XxR88OHqoZ3DvsOVcg+3qRL77NPrzkT/576YWAeGwHRAhz
2TBQQFH75S9iy+Iozw8u36+EMXp9ouXT0Ml+uIb2bd2s4+bi1aZKzCj+U82t30QQ
TNsBQ6MjS4DHyuTJCcduUmgtOvi77tJc4oj++bo2DKyk0ScImZy+3Eh5K4x4gF56
v4EC5Ykpjs0me424ej+Koxd90bCuyWnquzm1yxT3Wf09DOXtRrziwzshbJvbvkH6
6lupAoIBAQCxbllVJWRTAFgO7rc2BYM5PHzGLQwhWu8aSSYl4eRTGIlRsa83A6lB
GsUvoTZe6oVLDcZ3NKhfAYruxP1+iWKHk74wKXA3Z/5fU+mfkrXThSaObliDTgnwc1F6ZdpSnFOJtYoNtbqPv1Xt1mYT14McSPMuX2YoXWiGCxtNRMooxKSpDK1jwDHRLCNWl1QnnRlcYZ+hcSpLOERr7Vp3rSGZ6wETr9HeqaMGTiKABPs4vzUdX7s570WEjRuht5vyEBCPl/bDquM1ijnV9VfjDSiAc3Mro5G6BZT0tAVrzXIzvtjdHOqApGotTWXKSvQ/+RIWbA/Zxt6/M213YC/sEU0zAoIBAQDAvKLlQ9/+yJXIrEhnoe/HBnzQgeCFRsKF1xISsNsJIiP3smSve2XvvdBtfgWPRALWztyL17E08f54fGQ/oRhhnIinrva2kLJHdHE1dl4E2hLyp35hWU07WEFD0Bt9mCkQykSG1YxEmhYUS28Go+4X5kIlwESKO6TITmcrDNxKrc4uTWGB6MKdkOqX+hz5PmRLa/ANIzqLMRnUTHK5/Lc2/SOzHYzKGANiJhH6xOsTQU6tZI8n8JL//Yl4Y4vYMveb0Asy/nH4Pj0nqLRg6Ar2zdmgMtSx33RCalk5JLyxLY4FALMteCS6cTv1itP+Vx3OtX1FQrcERCwP8Fr4UDfO'

          SOURCE: "dist/"
          REMOTE_HOST: 118.89.219.85
          REMOTE_PORT: 13022
          REMOTE_USER: root
          TARGET: "/root/www/wiki-service"
          EXCLUDE: "/dist/, /node_modules/"
