name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2.4.1
      with:
        node-version: '14.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: 'MIICCgKCAgEAxbtk6R7qvSDR26g3xpOGxJmRkRctCLm9zxNReC3a+7meum6HI5A+sjNZJVYbbURZioBCaYQaBaZQlyhX0pDFMwobfqRNF0OjoFl2Ax9hVTW4vtkTl/TD6beaJFYjNQSzZhYXMULac3ALH114rcPRF1FqqAj/S6RWkj8sZ7xsVRh6VEerPhAdyOAFUCN6E+YM0WDlD8tLUp7a/v8JJTOUsm1aUsnCsHvkSYAKd7wiA5RXOx06Kz7w3rbt5LjkwAMXkAKy7JBM4cmQzP9r9w/8gQaVTNl8fb4EwX4xtapj8ZjQ2AL7m0V6O0TXY2ariMYCTa8E1Qybd91xnjUWhBWqmGZ1qyNEyU0lnRbbML9k7rx+oWAw2NrE5mJlSwoOyYp5oBOUiwon1TW+OQh+Xw3siIDB5/FrexN9vJCIEW5uvtKlSGEy61msF7RK+ec4bV0kv/gzonaUzeVGbHKHJVaQ2u94qJIBIRbeZh18u6yS77SRfADkPPMTvsNg3sa84sEPFZw3inK3KBk89uucRMGHMHm+kvDiFAouapQPC+Yy96v+RUr5xMg618vuACZxFxA57ydbd5TGxkWYkzpfHY79UKOXz5ZK+Ba6OmO8s2F2rk5wRjMxF5jWtzclImBWMy2x79zikGz21z4GYvdNaC+bkPC71uHutjbA2Xe1LqBynRMCAwEAAQ=='

          SOURCE: "dist/"
          REMOTE_HOST: 118.89.219.85
          REMOTE_PORT: 13022
          REMOTE_USER: root
          TARGET: "/root/www/wiki-service"
          EXCLUDE: "/dist/, /node_modules/"
