name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_DIR }}/dist/
            EXCLUDE: "/dist/, /node_modules/"
      - name: Install and Start
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SERVICE_HOST }}
            port: ${{ secrets.REMOTE_PORT }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              cd ${{ secrets.REMOTE_DIR }}
              git pull
              npm i
              npm run start:prod
#       - name: Install and Start
#         uses: appleboy/ssh-action@master
#         with:
#             host: ${{ secrets.SERVICE_HOST }}
#             port: ${{ secrets.SERVICE_PORT }}
#             username: ${{ secrets.SERVICE_USER_NAME }}
#             key: ${{ secrets.SERVICE_SSH_PRIVATE_KEY }}
#             script: |
#               cd /www/wwwroot/process.wendiaodiao.com/

