name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
#     - name: Install Node.js
#       uses: actions/setup-node@v2.4.1
#       with:
#         node-version: '14.x'
#     - name: Install npm dependencies
#       run: npm install
#     - name: Run build task
#       run: npm run build
#     - name: Deploy to Server
#       uses: easingthemes/ssh-deploy@main
#       env:
#           SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#           SOURCE: "/"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           TARGET: ${{ secrets.REMOTE_DIR }}
#           EXCLUDE: "/dist/, /node_modules/, tsconfig.json"
    - name: Install and Start
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SERVICE_HOST }}
          port: ${{ secrets.SERVICE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_DIR }}
            git pull
            npm i
            npm run start:prod
