name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install and Start
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SERVICE_HOST }}
            port: ${{ secrets.REMOTE_PORT }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
            script: |
              cd ${{ secrets.REMOTE_DIR }}
              git pull
              npm i
              npm run start:prod
